spring:
  datasource:
    url : jdbc:mysql://localhost:3306/EComFas?createDatabaseIfNotExist=true
    password: Thiwanka2003
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true